# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 04:36
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlpath',
            name='moved_from',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_to', to='wiki.URLPath'),
        ),
    ]
