# Generated by Django 3.0.3 on 2020-02-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_urlpath_moved_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlpath',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='urlpath',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='urlpath',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
