# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-05 23:27
from __future__ import unicode_literals

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_urlpath_moved_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='current_revision',
            field=models.OneToOneField(blank=True, help_text='The revision being displayed for this article. If you need to do a roll-back, simply change the value of this field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_set', to='wiki.ArticleRevision', verbose_name='current revision'),
        ),
        migrations.AlterField(
            model_name='revisionplugin',
            name='current_revision',
            field=models.OneToOneField(blank=True, help_text='The revision being displayed for this plugin. If you need to do a roll-back, simply change the value of this field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_set', to='wiki.RevisionPluginRevision', verbose_name='current revision'),
        ),
        migrations.AlterField(
            model_name='urlpath',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Position of URL path in the tree.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wiki.URLPath'),
        ),
    ]
