title: "[Feature] "
labels: ["Ideas"]
body:
  - type: checkboxes
    attributes:
      label: I've already checked other feature proposals
      required: true
  - type: dropdown
    attributes:
      label: Is your feature request related to a problem?
      options:
        - Yes
        - No
  - type: markdown
      attributes:
        label: Please describe your feature.
        required: true
        value: |
          A clear and concise description of what the problem is. Ex. I'm always frustrated when ...
  - type: markdown
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
      required: true
  - type: markdown
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: markdown
    attributes:
      label: Additional context.
      description: Add any other context or screenshots about the feature request here.
