title: "[Feature]: "
labels: ["ideas"]
body:
  - type: dropdown
    attributes:
      label: "I've already checked other feature proposals"
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Is your feature request related to a problem?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your problem.
      description: A clear and concise description of what the problem is.
  - type: textarea
    attributes:
      label: Describe your feature request.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else we should know.
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
        Add any other context or screenshots about the feature request here.
