version: 2.1

orbs:
  python: circleci/python@0.2.1
  codecov: codecov/codecov@3.2.5

jobs:
  hatch:
    parameters:
      hatch_env:
        description: "Name of Hatch environment to run"
        default: "py3.11-dj4.2"
        type: string
      python_version:
        description: "Python version string"
        default: "3.11"
        type: string
    description: "Reusable job for invoking hatch"
    docker:
      - image: cimg/python:<<parameters.python_version>>
    steps:
      - checkout
      - run: pip install hatch && python -m hatch --env test.<<parameters.hatch_env>> run all

  lint:
    description: "Simple job for linting the pushed code"
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install hatch && python -m hatch --env test.py3.11-dj4.2 run lint

  coverage:
    description: "Job to check the coverage"
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install coverage[toml]
      - run: pip install hatch && python -m hatch --env test.py3.11-dj4.2 run all
      - run: python -m coverage report -m
      - run: python -m coverage xml
      - codecov/upload


workflows:
  main:
    jobs:
      - hatch:
          hatch_env: "py3.9-dj3.2"
          python_version: "3.9"
      - hatch:
          hatch_env: "py3.9-dj4.0"
          python_version: "3.9"
      - hatch:
          hatch_env: "py3.9-dj4.1"
          python_version: "3.9"
      - hatch:
          hatch_env: "py3.9-dj4.2"
          python_version: "3.9"
      - hatch:
          hatch_env: "py3.10-dj3.2"
          python_version: "3.10"
      - hatch:
          hatch_env: "py3.10-dj4.0"
          python_version: "3.10"
      - hatch:
          hatch_env: "py3.10-dj4.1"
          python_version: "3.10"
      - hatch:
          hatch_env: "py3.10-dj4.2"
          python_version: "3.10"
      - hatch:
          hatch_env: "py3.11-dj4.1"
          python_version: "3.11"
      - hatch:
          hatch_env: "py3.11-dj4.2"
          python_version: "3.11"
      - lint
      - coverage
