# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0002_urlpath_moved_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('articleplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wiki.ArticlePlugin')),
                ('key', models.CharField(max_length=28)),
                ('val', models.TextField()),
                ('owner', models.ForeignKey(help_text='The author of the input. The owner always has both read access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_inputs', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Input',
                'verbose_name_plural': 'Inputs',
                'get_latest_by': 'created',
            },
            bases=('wiki.articleplugin',),
        ),
    ]
