# Generated by Django 5.2.15 on 2026-06-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki_attachments", "0002_auto_20151118_1816"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentrevision",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
