# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-05 23:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_attachments', '0002_auto_20151118_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='current_revision',
            field=models.OneToOneField(blank=True, help_text='The revision of this attachment currently in use (on all articles using the attachment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_set', to='wiki_attachments.AttachmentRevision', verbose_name='current revision'),
        ),
    ]
